# Utilisation de Python 3.12 sur base Debian Bookworm (très stable)
FROM mcr.microsoft.com/devcontainers/python:3.12-bookworm
# Installation de 'uv' via le binaire officiel
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/bin/uv